#!/usr/bin/env python
"""Per-device I_D(V_DS) curvature -- the input to the drain-conductance distortion test.

THE HYPOTHESIS THIS SERVES, stated before the measurement (repo rule 3).

  H: the third harmonic that `validation.md` Section 6.2 reports as unexplained below
     35 Hz -- 0.18-0.28 uV, and nearly CONSTANT IN VOLTS while the modelled mechanism
     moves by 39x over the same span -- is generated by drain-conductance nonlinearity,
     i.e. the curvature of I_D in V_DS.  The gate-referred exponential model does not
     contain it, and the small-signal Z_T linearises it away by construction.

  Two independent predictions, both of which must hold:
     P1 magnitude   -- the third-order term, propagated by the SAME Z_T, lands within a
                       factor of 3 of the measured 0.18-0.28 uV.
     P2 frequency   -- it is flat in volts below 35 Hz, because the drain swing is set by
                       the output swing (flat in the passband) and not by the feedback
                       error (which scales with w).

  REFUTATION: a predicted amplitude more than 10x away from the residual, or a frequency
  slope of the wrong sign, refutes H.  A refutation is a result and gets reported as one;
  the point of writing the threshold down first is that it cannot move afterwards.

This script does the measurement half: for every device, a standalone probe pinned to the
device's own operating point by ABSOLUTE NODE VOLTAGES (never PSP's sign-folded `vgs`),
swept in V_DS, with a cubic fitted to the drain current.  `gds_residual.py` does the
propagation half in the symbolic lane.

    LPF_NGSPICE=... PDK_ROOT=... .venv/bin/python \\
        signoff/paper-draft/scripts/gds_probe.py
"""
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
OUT = HERE.parent / "data"
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(HERE))

os.environ.setdefault("PDK_ROOT", os.path.expanduser("~/local/pdks"))
os.environ.setdefault("PDK", "ihp-sg13g2")
os.environ.setdefault("LPF_NGSPICE", os.path.expanduser("~/local/bin/ngspice"))

import numpy as np  # noqa: E402

from extract_bench import MOS_CARD, dut_design  # noqa: E402
from lab import ngspice as ng, raw as R  # noqa: E402
from lab.deck import _libs  # noqa: E402
from lab.dut import subckt  # noqa: E402
from lab.parallel import batch  # noqa: E402

LABEL = "pre_mim"
#: Half-widths to fit over, in volts.  Three of them on purpose: a cubic coefficient that
#: changes with the window is not a local derivative, it is a curve-fitting artefact, and
#: the spread across these windows is reported so the reader can see which it is.
WINDOWS = (0.015, 0.030, 0.060)
NPTS = 81


def cards(d) -> dict[str, dict]:
    """{instance: {nets, model, params}} straight off the DUT netlist."""
    out = {}
    for m in MOS_CARD.finditer(subckt(d)):
        ref, dn, gn, sn, bn, model, rest = m.group(1), *m.group(2, 3, 4, 5), m.group(6), m.group(7)
        out[ref[1:]] = {"ref": ref, "nets": {"d": dn, "g": gn, "s": sn, "b": bn},
                        "model": model, "params": rest.strip()}
    return out


def probe_deck(d, card: dict, v: dict, win: float) -> str:
    """One device, pinned at its in-circuit bias, swept in V_DS.

    Every terminal is driven by an absolute-voltage source taken from the DUT's own
    operating point, so the probe reproduces the device's state without re-deriving any
    model sign convention.  `vd` is the swept source; `i(vd)` is its current, and the
    drain current into the device is its negative.
    """
    lo, hi = v["d"] - win, v["d"] + win
    return f""".title gds probe {card['ref']}
{_libs(d=d)}
vd nd 0 {v['d']:.9g}
vg ng 0 {v['g']:.9g}
vs ns 0 {v['s']:.9g}
vb nb 0 {v['b']:.9g}
{card['ref']} nd ng ns nb {card['model']} {card['params']}
.control
set filetype=binary
dc vd {lo:.9g} {hi:.9g} {(hi - lo) / (NPTS - 1):.9g}
write sim.raw
.endc
.end
"""


def fit_cubic(v: np.ndarray, i: np.ndarray, v0: float) -> dict:
    """I(v) = I0 + g1*x + g2*x^2/2 + g3*x^3/6 about x = v - v0.

    Returned as the Taylor coefficients themselves (g1 = g_ds, g2 = dg_ds/dV_DS,
    g3 = d2g_ds/dV_DS2), because those are what the harmonic algebra uses.  Fitting a
    polynomial rather than differencing twice is deliberate: two numerical derivatives of
    a subthreshold I-V are dominated by solver noise.
    """
    x = v - v0
    c = np.polyfit(x, i, 3)                      # c[0]*x^3 + c[1]*x^2 + c[2]*x + c[3]
    resid = i - np.polyval(c, x)
    scale = max(float(np.max(np.abs(i - i.mean()))), 1e-30)
    return {"i0": float(c[3]), "g1": float(c[2]), "g2": float(2 * c[1]),
            "g3": float(6 * c[0]),
            "fit_rel_residual": float(np.max(np.abs(resid)) / scale)}


def main() -> None:
    d, cell, _ = dut_design(LABEL)
    bench = json.loads((OUT / f"bench_{LABEL}.json").read_text())
    nodes, ops, cs = bench["nodes"], bench["op"], cards(d)

    jobs = [(inst, cs[inst], w) for inst in ops if inst in cs for w in WINDOWS]

    def one(job):
        inst, card, w = job
        v = {t: (0.0 if n == "0" else nodes[n]) for t, n in card["nets"].items()}
        plots = ng.plots(ng.run(probe_deck(d, card, v, w), f"gds_{inst}_w{w*1e3:.0f}"))
        dc = R.pick(plots, "dc")
        vv = np.asarray(np.real(dc["v(nd)"]), float)
        ii = -np.asarray(np.real(dc["i(vd)"]), float)
        return inst, w, fit_cubic(vv, ii, v["d"])

    devs: dict[str, dict] = {}
    for r in batch(jobs, one):
        if isinstance(r, BaseException):
            print(f"  probe failed: {r!r}")
            continue
        inst, w, fit = r
        devs.setdefault(inst, {"role": ops[inst].get("role"),
                               "model": ops[inst]["model"],
                               "nets": cs[inst]["nets"],
                               "gds_op": ops[inst]["gds"],
                               "ids_op": ops[inst]["ids"], "windows": {}})
        devs[inst]["windows"][f"{w:g}"] = fit

    print(f"{'inst':6s} {'role':14s} {'g1 (S)':>12s} {'gds op':>12s} "
          f"{'g3 (A/V3)':>12s} {'g3 spread':>10s} {'fit resid':>10s}")
    for inst, rec in devs.items():
        w = rec["windows"]
        ref = w[f"{WINDOWS[1]:g}"]
        g3s = [w[f"{x:g}"]["g3"] for x in WINDOWS]
        spread = (max(g3s) / min(g3s)) if min(g3s) > 0 else float("nan")
        rec["g1"], rec["g2"], rec["g3"] = ref["g1"], ref["g2"], ref["g3"]
        rec["g3_window_spread_x"] = float(spread)
        rec["g1_vs_gds_op_pct"] = 100.0 * (ref["g1"] - rec["gds_op"]) / rec["gds_op"]
        print(f"{inst:6s} {str(rec['role']):14s} {ref['g1']:12.4e} {rec['gds_op']:12.4e} "
              f"{ref['g3']:12.4e} {spread:10.3f} {ref['fit_rel_residual']:10.2e}")

    worst = max(abs(r["g1_vs_gds_op_pct"]) for r in devs.values())
    print(f"\nprobe g1 vs the DUT's own PSP gds: worst {worst:.3f} % "
          f"-- the probe reproduces the in-circuit operating point")
    (OUT / "gds_taylor.json").write_text(json.dumps(
        {"cell": cell, "label": LABEL, "windows_v": list(WINDOWS), "npts": NPTS,
         "worst_g1_vs_gds_op_pct": worst, "devices": devs}, indent=1))
    print(f"wrote {(OUT / 'gds_taylor.json').relative_to(REPO)}")


if __name__ == "__main__":
    main()
